[phases.setup]
nixpkgs = ["python39", "pip", "ffmpeg"]

[phases.install]
commands = [
  "pip install -r requirements.txt"
]

[phases.build]
commands = [
  "echo 'Build phase completed'"
]

[phases.start]
commands = [
  "flask -app run_app run --host=0.0.0.0 --port=8000"
]
